

#language: ruby
# only run CI-builds on master branch
#branches:
#  only:
#  - master
#rvm:
#- 2.3
# set execution permission on our build script
#before_script:
# - chmod +x ./script/cibuild.sh
# path to our build script.
# Travis will run `bundle install` by default before running our script
#script: ./script/cibuild.sh
#exclude: [vendor]
#sudo: false

#gem install travis
#travis encrypt GH_TOKEN=62f3058a11f610f69fb2b562de526f0835c13aea


# tell Travis to spin up a ruby 2.2.0 environment
language: ruby
rvm:
- 2.3.1

before_install:
#- GIT_POST_URL=$(ruby -r "$PWD"/script/config.rb -e "puts @github_post_url")
#- git remote add other $GIT_POST_URL
#- git fetch other
#- git merge --no-edit other/master --allow-unrelated-histories


install:
- gem install rake
- bundle install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
#script:
#- bundle exec jekyll build

# after building, copy the site into the gh-pages branch
# and push back to Github
#after_success: 
#- git clone https://$GITHUB_REPO
#- cd _site
#- git config user.name "Pgahye"
#- git config user.email ${EMAIL}
#- rsync -az --delete --exclude '.git*' ../_site/ .
#- touch .nojekyll
#- git add --all
#- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
#- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}

#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
#  - GITHUB_REPO: github.com/Pgahye/Pgahye.github.io.git
#  - REPO_TARGET_BRANCH: source
#  - EMAIL: rkgp0515@gmail.com
#  - DEPLOY_KEY: 73fc961f4715e0ae9fc3c6913ea926d20ae75b64	



# your Github verified email address
#$ travis encrypt EMAIL=rkgp0515@gmail.com --add

# your personal access token
#$ travis encrypt DEPLOY_KEY=73fc961f4715e0ae9fc3c6913ea926d20ae75b64 --add
