


## 사이트 설정
title: 하이브레인넷 부설연구소
twitter : https://twitter.com/hibrainnet
facebook : https://www.facebook.com/하이브레인넷-부설연구소-488747181169148/
email: apps@hibrain.net
description: >-
# baseurl: "/jekyll-and-hybe"
url: "http://blog.hibrainapps.net"

## git 설정
git:
  admins: ## admins에 등록된 사용자만 master에 commit, merge, push를 진행할 수 있음
    - sksong@hibrain.net
    - saltfactory@gmail.com


# Google Analytics
google_analytics: UA-18071244-5    


github_post:
    remote_url: https://Pgahye:${GIHUB_TOKEN}@github.com/Pgahye/Pgahye.github.io.git


## Medium tokens 설정
medium:
  integration_token: ${MEDIUM_TOKEN}

## github 설정
github_page:
  remote_url: /Pgahye/post.git
  branch: source
  token: personal_access_token
  builder: travis

## travis를 이용한 github page 빌드 설정
travis:
  github_token: ${GIHUB_TOKEN}
  target_branch: master
  source_branch: source
  repository_path: Pgahye/post

# github_username:  hibrainnet

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-compose
  - jekyll-seo-tag

include: ['_pages']

exclude:
  - vendor
  - Gemfile
  - Geffile.lock
  - LICENSE
  - README.md
  - Rakefile

#pre-push hook 변수
#githubURL=소스코드를 push할 URL
#githubBranch=소스코트를 push할 Branch
#remoteName=소스코드를 보낼 remote 이름
githubURL: git@github.com:hibrainnet/jekyll-and-hybe.git
githubBranch: source
remoteName: github
